[tool.poetry]
name = "gogettr"
version = "0.9.2"
description = "Extraction tool for GETTR, a \"non-bias [sic] social network.\""
authors = ["Stanford Internet Observatory <mccain@stanford.edu>"]
license = "Apache-2.0"
homepage = "https://github.com/stanfordio/gogettr"
keywords = ["gettr", "scraper", "cli"]
packages = [
    {include = "gogettr"}
]
readme = "README.md"

[tool.poetry.scripts]
gogettr = "gogettr.cli:cli"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.33"
click = "^8.3"

[tool.poetry.group.dev.dependencies]
black = "^26.3"
pytest = "^9.0"
pylint = "^4.0"

[build-system]
requires = ["poetry-core>=1.9.1"]
build-backend = "poetry.core.masonry.api"
